// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Anti_windup.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Anti_windup
// Source Path: PIDforVerilog/Discrete PID Controller/Anti-windup
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Anti_windup
          (preSat,
           preInt,
           Out1);


  input   signed [31:0] preSat;  // sfix32_En16
  input   signed [31:0] preInt;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Disc_Clamping_Parallel_out1;  // sfix32_En16


  Disc_Clamping_Parallel u_Disc_Clamping_Parallel (.preSat(preSat),  // sfix32_En16
                                                   .preInt(preInt),  // sfix32_En16
                                                   .Out1(Disc_Clamping_Parallel_out1)  // sfix32_En16
                                                   );

  assign Out1 = Disc_Clamping_Parallel_out1;

endmodule  // Anti_windup

