// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Dead_Zone.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Dead_Zone
// Source Path: PIDforVerilog/Discrete PID Controller/Anti-windup/Disc. Clamping Parallel/Dead Zone
// Hierarchy Level: 4
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Dead_Zone
          (preSat,
           DZ_out);


  input   signed [31:0] preSat;  // sfix32_En16
  output  signed [31:0] DZ_out;  // sfix32_En16


  wire signed [31:0] Enabled_out1;  // sfix32_En16


  Enabled u_Enabled (.preSat(preSat),  // sfix32_En16
                     .DZ_out(Enabled_out1)  // sfix32_En16
                     );

  assign DZ_out = Enabled_out1;

endmodule  // Dead_Zone

