// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Discrete.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Discrete
// Source Path: PIDforVerilog/Discrete PID Controller/Integrator/Discrete
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Discrete
          (clk,
           reset,
           enb,
           U,
           out);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] U;  // sfix32_En16
  output  signed [31:0] out;  // sfix32_En16


  wire signed [31:0] Integrator_indtc;  // sfix32
  wire signed [32:0] gain_cast;  // sfix33_En7
  wire signed [31:0] Integrator_u_gain;  // sfix32
  wire signed [31:0] Integrator_u_dtc;  // sfix32_En16
  reg signed [31:0] Integrator_x_reg;  // sfix32_En16
  wire signed [32:0] adder_add_cast;  // sfix33_En16
  wire signed [32:0] adder_add_cast_1;  // sfix33_En16
  wire signed [32:0] adder_add_temp;  // sfix33_En16
  wire signed [31:0] Integrator_u_add;  // sfix32_En16
  wire signed [31:0] Integrator_u_sat;  // sfix32_En16


  assign Integrator_indtc = U;

  assign gain_cast = {Integrator_indtc[31], Integrator_indtc};
  assign Integrator_u_gain = {{6{gain_cast[32]}}, gain_cast[32:7]};

  assign Integrator_u_dtc = Integrator_u_gain;

  assign adder_add_cast = {Integrator_x_reg[31], Integrator_x_reg};
  assign adder_add_cast_1 = {Integrator_u_dtc[31], Integrator_u_dtc};
  assign adder_add_temp = adder_add_cast + adder_add_cast_1;
  assign Integrator_u_add = ((adder_add_temp[32] == 1'b0) && (adder_add_temp[31] != 1'b0) ? 32'sb01111111111111111111111111111111 :
              ((adder_add_temp[32] == 1'b1) && (adder_add_temp[31] != 1'b1) ? 32'sb10000000000000000000000000000000 :
              $signed(adder_add_temp[31:0])));

  assign Integrator_u_sat = (Integrator_u_add > 32'sb00000000011001000000000000000000 ? 32'sb00000000011001000000000000000000 :
              (Integrator_u_add < 32'sb11111111100111000000000000000000 ? 32'sb11111111100111000000000000000000 :
              Integrator_u_add));

  always @(posedge clk or posedge reset)
    begin : Integrator_reg_process
      if (reset == 1'b1) begin
        Integrator_x_reg <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Integrator_x_reg <= Integrator_u_sat;
        end
      end
    end

  assign out = Integrator_x_reg;

endmodule  // Discrete

