// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Disc_Clamping_Parallel.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Disc_Clamping_Parallel
// Source Path: PIDforVerilog/Discrete PID Controller/Anti-windup/Disc. Clamping Parallel
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Disc_Clamping_Parallel
          (preSat,
           preInt,
           Out1);


  input   signed [31:0] preSat;  // sfix32_En16
  input   signed [31:0] preInt;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Clamping_zero_out1;  // sfix32_En16
  wire signed [31:0] Dead_Zone_out1;  // sfix32_En16
  wire fix_for_DT_propagation_issue_out1;
  wire switch_compare_1;
  wire signed [7:0] Constant2_out1;  // int8
  wire fix_for_DT_propagation_issue1_out1;
  wire switch_compare_1_1;
  wire signed [7:0] Constant4_out1;  // int8
  wire Relational_Operator_out1;
  wire signed [7:0] Constant_out1;  // int8
  wire signed [7:0] Switch1_out1;  // int8
  wire signed [7:0] Constant3_out1;  // int8
  wire signed [7:0] Switch2_out1;  // int8
  wire Equal1_out1;
  wire AND3_out1;
  wire switch_compare_1_2;
  wire signed [31:0] Constant1_out1;  // sfix32_En16
  wire signed [31:0] Switch_out1;  // sfix32_En16


  assign Clamping_zero_out1 = 32'sb00000000000000000000000000000000;

  Dead_Zone u_Dead_Zone (.preSat(preSat),  // sfix32_En16
                         .DZ_out(Dead_Zone_out1)  // sfix32_En16
                         );

  assign fix_for_DT_propagation_issue_out1 = Dead_Zone_out1 > Clamping_zero_out1;

  assign switch_compare_1 = fix_for_DT_propagation_issue_out1 > 1'b0;

  assign Constant2_out1 = 8'sb11111111;

  assign fix_for_DT_propagation_issue1_out1 = preInt > Clamping_zero_out1;

  assign switch_compare_1_1 = fix_for_DT_propagation_issue1_out1 > 1'b0;

  assign Constant4_out1 = 8'sb11111111;

  assign Relational_Operator_out1 = Clamping_zero_out1 != Dead_Zone_out1;

  assign Constant_out1 = 8'sb00000001;

  assign Switch1_out1 = (switch_compare_1 == 1'b0 ? Constant2_out1 :
              Constant_out1);

  assign Constant3_out1 = 8'sb00000001;

  assign Switch2_out1 = (switch_compare_1_1 == 1'b0 ? Constant4_out1 :
              Constant3_out1);

  assign Equal1_out1 = Switch1_out1 == Switch2_out1;

  assign AND3_out1 = Relational_Operator_out1 & Equal1_out1;

  assign switch_compare_1_2 = AND3_out1 > 1'b0;

  assign Constant1_out1 = 32'sb00000000000000000000000000000000;

  assign Switch_out1 = (switch_compare_1_2 == 1'b0 ? preInt :
              Constant1_out1);

  assign Out1 = Switch_out1;

endmodule  // Disc_Clamping_Parallel

