// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Enabled_block.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Enabled_block
// Source Path: PIDforVerilog/Discrete PID Controller/Saturation/Enabled
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Enabled_block
          (In1,
           Out1);


  input   signed [31:0] In1;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Saturation_out1;  // sfix32_En16


  assign Saturation_out1 = (In1 > 32'sb00001111111111110000000000000000 ? 32'sb00001111111111110000000000000000 :
              (In1 < 32'sb11110000000000010000000000000000 ? 32'sb11110000000000010000000000000000 :
              In1));

  assign Out1 = Saturation_out1;

endmodule  // Enabled_block

