// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/External_Derivative.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: External_Derivative
// Source Path: PIDforVerilog/Discrete PID Controller/External Derivative
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module External_Derivative
          (err,
           Out1);


  input   signed [31:0] err;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] error_signal;  // sfix32_En16


  Error u_Error (.err(err),  // sfix32_En16
                 .Out1(error_signal)  // sfix32_En16
                 );

  assign Out1 = error_signal;

endmodule  // External_Derivative

