// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Forward_Path.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Forward_Path
// Source Path: PIDforVerilog/Discrete PID Controller/preSat Signal/Forward_Path
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Forward_Path
          (forward,
           Out1);


  input   signed [31:0] forward;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16




  assign Out1 = forward;

endmodule  // Forward_Path

