// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/I_Gain.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: I_Gain
// Source Path: PIDforVerilog/Discrete PID Controller/I Gain
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module I_Gain
          (err,
           Out1);


  input   signed [31:0] err;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Internal_Parameters_out1;  // sfix32_En16


  Internal_Parameters_block u_Internal_Parameters (.err(err),  // sfix32_En16
                                                   .Out1(Internal_Parameters_out1)  // sfix32_En16
                                                   );

  assign Out1 = Internal_Parameters_out1;

endmodule  // I_Gain

