// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Ideal_P_Gain.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Ideal_P_Gain
// Source Path: PIDforVerilog/Discrete PID Controller/Ideal P Gain
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Ideal_P_Gain
          (In1,
           Out1);


  input   signed [31:0] In1;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Passthrough_out1;  // sfix32_En16


  Passthrough u_Passthrough (.In1(In1),  // sfix32_En16
                             .Out1(Passthrough_out1)  // sfix32_En16
                             );

  assign Out1 = Passthrough_out1;

endmodule  // Ideal_P_Gain

