// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Internal_Parameters_block2.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Internal_Parameters_block2
// Source Path: PIDforVerilog/Discrete PID Controller/Parallel P Gain/Internal Parameters
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Internal_Parameters_block2
          (err,
           Out1);


  input   signed [31:0] err;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [63:0] Proportional_Gain_cast;  // sfix64_En32
  wire signed [31:0] Proportional_Gain_out1;  // sfix32_En16


  assign Proportional_Gain_cast = {{30{err[31]}}, {err, 2'b00}};
  assign Proportional_Gain_out1 = ((Proportional_Gain_cast[63] == 1'b0) && (Proportional_Gain_cast[62:47] != 16'b0000000000000000) ? 32'sb01111111111111111111111111111111 :
              ((Proportional_Gain_cast[63] == 1'b1) && (Proportional_Gain_cast[62:47] != 16'b1111111111111111) ? 32'sb10000000000000000000000000000000 :
              $signed(Proportional_Gain_cast[47:16])));

  assign Out1 = Proportional_Gain_out1;

endmodule  // Internal_Parameters_block2

