// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Internal_Parameters_block.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Internal_Parameters_block
// Source Path: PIDforVerilog/Discrete PID Controller/I Gain/Internal Parameters
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Internal_Parameters_block
          (err,
           Out1);


  input   signed [31:0] err;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Integral_Gain_out1;  // sfix32_En16


  assign Integral_Gain_out1 = 32'sb00000000000000000000000000000000;

  assign Out1 = Integral_Gain_out1;

endmodule  // Internal_Parameters_block

