// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Internal_Parameters_block1.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Internal_Parameters_block1
// Source Path: PIDforVerilog/Discrete PID Controller/N Gain/Internal Parameters
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Internal_Parameters_block1
          (U,
           Out1);


  input   signed [31:0] U;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [63:0] Filter_Coefficient_mul_temp;  // sfix64_En32
  wire signed [31:0] Filter_Coefficient_out1;  // sfix32_En16


  assign Filter_Coefficient_mul_temp = 32'sb00000000011001000000000000000000 * U;
  assign Filter_Coefficient_out1 = ((Filter_Coefficient_mul_temp[63] == 1'b0) && (Filter_Coefficient_mul_temp[62:47] != 16'b0000000000000000) ? 32'sb01111111111111111111111111111111 :
              ((Filter_Coefficient_mul_temp[63] == 1'b1) && (Filter_Coefficient_mul_temp[62:47] != 16'b1111111111111111) ? 32'sb10000000000000000000000000000000 :
              $signed(Filter_Coefficient_mul_temp[47:16])));

  assign Out1 = Filter_Coefficient_out1;

endmodule  // Internal_Parameters_block1

