// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Integrator.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Integrator
// Source Path: PIDforVerilog/Discrete PID Controller/Integrator
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Integrator
          (clk,
           reset,
           enb,
           U,
           out);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] U;  // sfix32_En16
  output  signed [31:0] out;  // sfix32_En16


  wire signed [31:0] Discrete_out1;  // sfix32_En16


  Discrete u_Discrete (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .U(U),  // sfix32_En16
                       .out(Discrete_out1)  // sfix32_En16
                       );

  assign out = Discrete_out1;

endmodule  // Integrator

