// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Parallel_P_Gain.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Parallel_P_Gain
// Source Path: PIDforVerilog/Discrete PID Controller/Parallel P Gain
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Parallel_P_Gain
          (err,
           Out1);


  input   signed [31:0] err;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Internal_Parameters_out1;  // sfix32_En16


  Internal_Parameters_block2 u_Internal_Parameters (.err(err),  // sfix32_En16
                                                    .Out1(Internal_Parameters_out1)  // sfix32_En16
                                                    );

  assign Out1 = Internal_Parameters_out1;

endmodule  // Parallel_P_Gain

