// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Passthrough.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Passthrough
// Source Path: PIDforVerilog/Discrete PID Controller/Ideal P Gain/Passthrough
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Passthrough
          (In1,
           Out1);


  input   signed [31:0] In1;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16




  assign Out1 = In1;

endmodule  // Passthrough

