// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Passthrough_block.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Passthrough_block
// Source Path: PIDforVerilog/Discrete PID Controller/Tracking Mode Sum/Passthrough
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Passthrough_block
          (fromIgain,
           preInt);


  input   signed [31:0] fromIgain;  // sfix32_En16
  output  signed [31:0] preInt;  // sfix32_En16




  assign preInt = fromIgain;

endmodule  // Passthrough_block

