// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/preInt_Signal.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: preInt_Signal
// Source Path: PIDforVerilog/Discrete PID Controller/preInt Signal
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module preInt_Signal
          (preInt,
           Out1);


  input   signed [31:0] preInt;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Internal_PreInt_out1;  // sfix32_En16


  Internal_PreInt u_Internal_PreInt (.preInt(preInt),  // sfix32_En16
                                     .Out1(Internal_PreInt_out1)  // sfix32_En16
                                     );

  assign Out1 = Internal_PreInt_out1;

endmodule  // preInt_Signal

