// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/preSat_Signal.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: preSat_Signal
// Source Path: PIDforVerilog/Discrete PID Controller/preSat Signal
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module preSat_Signal
          (forward,
           Out1);


  input   signed [31:0] forward;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Forward_Path_out1;  // sfix32_En16


  Forward_Path u_Forward_Path (.forward(forward),  // sfix32_En16
                               .Out1(Forward_Path_out1)  // sfix32_En16
                               );

  assign Out1 = Forward_Path_out1;

endmodule  // preSat_Signal

