// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Saturation.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Saturation
// Source Path: PIDforVerilog/Discrete PID Controller/Saturation
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Saturation
          (In1,
           Out1);


  input   signed [31:0] In1;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Enabled_out1;  // sfix32_En16


  Enabled_block u_Enabled (.In1(In1),  // sfix32_En16
                           .Out1(Enabled_out1)  // sfix32_En16
                           );

  assign Out1 = Enabled_out1;

endmodule  // Saturation

