// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Sum_PID.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sum_PID
// Source Path: PIDforVerilog/Discrete PID Controller/Sum/Sum_PID
// Hierarchy Level: 3
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sum_PID
          (P,
           I,
           D,
           Out1);


  input   signed [31:0] P;  // sfix32_En16
  input   signed [31:0] I;  // sfix32_En16
  input   signed [31:0] D;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [32:0] Sum_stage2_add_cast;  // sfix33_En16
  wire signed [32:0] Sum_stage2_add_cast_1;  // sfix33_En16
  wire signed [32:0] Sum_stage2_add_temp;  // sfix33_En16
  wire signed [31:0] Sum_stage2_cast;  // sfix32_En16
  wire signed [32:0] Sum_op_stage1;  // sfix33_En16
  wire signed [31:0] Sum_stage3_add_cast;  // sfix32_En16
  wire signed [32:0] Sum_stage3_add_cast_1;  // sfix33_En16
  wire signed [32:0] Sum_stage3_add_cast_2;  // sfix33_En16
  wire signed [32:0] Sum_stage3_add_temp;  // sfix33_En16
  wire signed [31:0] Sum_out1;  // sfix32_En16


  assign Sum_stage2_add_cast = {P[31], P};
  assign Sum_stage2_add_cast_1 = {I[31], I};
  assign Sum_stage2_add_temp = Sum_stage2_add_cast + Sum_stage2_add_cast_1;
  assign Sum_stage2_cast = ((Sum_stage2_add_temp[32] == 1'b0) && (Sum_stage2_add_temp[31] != 1'b0) ? 32'sb01111111111111111111111111111111 :
              ((Sum_stage2_add_temp[32] == 1'b1) && (Sum_stage2_add_temp[31] != 1'b1) ? 32'sb10000000000000000000000000000000 :
              $signed(Sum_stage2_add_temp[31:0])));
  assign Sum_op_stage1 = {Sum_stage2_cast[31], Sum_stage2_cast};

  assign Sum_stage3_add_cast = ((Sum_op_stage1[32] == 1'b0) && (Sum_op_stage1[31] != 1'b0) ? 32'sb01111111111111111111111111111111 :
              ((Sum_op_stage1[32] == 1'b1) && (Sum_op_stage1[31] != 1'b1) ? 32'sb10000000000000000000000000000000 :
              $signed(Sum_op_stage1[31:0])));
  assign Sum_stage3_add_cast_1 = {Sum_stage3_add_cast[31], Sum_stage3_add_cast};
  assign Sum_stage3_add_cast_2 = {D[31], D};
  assign Sum_stage3_add_temp = Sum_stage3_add_cast_1 + Sum_stage3_add_cast_2;
  assign Sum_out1 = ((Sum_stage3_add_temp[32] == 1'b0) && (Sum_stage3_add_temp[31] != 1'b0) ? 32'sb01111111111111111111111111111111 :
              ((Sum_stage3_add_temp[32] == 1'b1) && (Sum_stage3_add_temp[31] != 1'b1) ? 32'sb10000000000000000000000000000000 :
              $signed(Sum_stage3_add_temp[31:0])));

  assign Out1 = Sum_out1;

endmodule  // Sum_PID

