// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Tracking_Mode_Sum.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Tracking_Mode_Sum
// Source Path: PIDforVerilog/Discrete PID Controller/Tracking Mode Sum
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Tracking_Mode_Sum
          (fromIgain,
           preInt);


  input   signed [31:0] fromIgain;  // sfix32_En16
  output  signed [31:0] preInt;  // sfix32_En16


  wire signed [31:0] Passthrough_out1;  // sfix32_En16


  Passthrough_block u_Passthrough (.fromIgain(fromIgain),  // sfix32_En16
                                   .preInt(Passthrough_out1)  // sfix32_En16
                                   );

  assign preInt = Passthrough_out1;

endmodule  // Tracking_Mode_Sum

