// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Tsamp_Ngain.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Tsamp_Ngain
// Source Path: PIDforVerilog/Discrete PID Controller/Tsamp - Ngain
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Tsamp_Ngain
          (U,
           Out1);


  input   signed [31:0] U;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] Passthrough_out1;  // sfix32_En16


  Passthrough_block1 u_Passthrough (.U(U),  // sfix32_En16
                                    .Out1(Passthrough_out1)  // sfix32_En16
                                    );

  assign Out1 = Passthrough_out1;

endmodule  // Tsamp_Ngain

