// -------------------------------------------------------------
// 
// File Name: hdlsrc/PIDforVerilog/Tsamp_Integral.v
// Created: 2025-06-05 14:36:24
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Tsamp_Integral
// Source Path: PIDforVerilog/Discrete PID Controller/Tsamp - Integral
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Tsamp_Integral
          (U,
           Out1);


  input   signed [31:0] U;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En16


  wire signed [31:0] TsSignalSpecification_out1;  // sfix32_En16


  TsSignalSpecification u_TsSignalSpecification (.U(U),  // sfix32_En16
                                                 .Out1(TsSignalSpecification_out1)  // sfix32_En16
                                                 );

  assign Out1 = TsSignalSpecification_out1;

endmodule  // Tsamp_Integral

